# 开发环境
spring:
  profiles:
    active: dev

# MyBatis Plus
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Logback
logging:
  config: classpath:logback.xml

# JWT
jwt:
  # JWT 加解密使用的密钥
  secret: Uldi(*&F123llUPoo$@
  # JWT 存储的请求头
  header: X-Auth-Token
  # JWT AccessToken 过期时间(60*60*24*7 604800)
  accessTokenExpireTime: 604800

# 阿里云 OSS
aliyun:
  oss:
    bucket-name: codetc
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: accessKeyId
    access-key-secret: accessKeySecret
    dir: images
    # bucket 绑定用户域名(图片需要绑定域名才能预览)
    preview-url: http://images.zhomi.com
    # 可上传的文件类型
    accept-type: [jpg,png,gif,jpeg,bmp]

# 认证
auth:
  # 忽略认证的接口
  ignored:
    urls:
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /webjars/springfox-swagger-ui/**
    - /**/v2/api-docs
    - /druid/**
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /auth/login
    - /auth/register
    - /auth/logout
    - /hello/index